#ifndef __DATA
#define __DATA

#include "heavy_pcx.h"

#include "heavy_walk_01_bin.h"
#include "heavy_walk_02_bin.h"
#include "heavy_walk_03_bin.h"
#include "heavy_walk_04_bin.h"
#include "heavy_walk_05_bin.h"
#include "heavy_walk_06_bin.h"
#include "heavy_walk_07_bin.h"
#include "heavy_walk_08_bin.h"
#include "heavy_walk_09_bin.h"
#include "heavy_walk_10_bin.h"
#include "heavy_walk_11_bin.h"
#include "heavy_walk_12_bin.h"
#include "heavy_walk_13_bin.h"
#include "heavy_walk_14_bin.h"
#include "heavy_walk_15_bin.h"
#include "heavy_walk_16_bin.h"
#include "heavy_walk_17_bin.h"
#include "heavy_walk_18_bin.h"
#include "heavy_walk_19_bin.h"
#include "heavy_walk_20_bin.h"
#include "heavy_walk_21_bin.h"
#include "heavy_walk_22_bin.h"
#include "heavy_walk_23_bin.h"
#include "heavy_walk_24_bin.h"
#include "heavy_walk_25_bin.h"
#include "heavy_walk_26_bin.h"
#include "heavy_walk_27_bin.h"
#include "heavy_walk_28_bin.h"
#include "heavy_walk_29_bin.h"
#include "heavy_walk_30_bin.h"
#include "heavy_walk_31_bin.h"
#include "heavy_walk_32_bin.h"
#include "heavy_walk_33_bin.h"
#include "heavy_walk_34_bin.h"
#include "heavy_walk_35_bin.h"
#include "heavy_walk_36_bin.h"
#include "heavy_walk_37_bin.h"
#include "heavy_walk_38_bin.h"
#include "heavy_walk_39_bin.h"
#include "heavy_walk_40_bin.h"


#endif //__DATA
